### ISSUE TITLE
activity recognition Chapter in scalable-data-science course

### ISSUE THREAD

**Issue by lamastex** [MiraLak/activityRecognitionV2#1]
Dear MiraLak,

I have been watching your video on activity recognition enthusiastically!

I have been meaning to ask you about the training data your colleagues helped you collect.
It looks like you have recently pushed them to github, right?

Do you mind if I used your codes and data in a course in scalable data science I may be offering in January at Uppsala University, Uppsala, Sweden?
You will get all the credits for your code, of course. I may just have to doctor them a bit more by embedding more explanations with background readings, etc as done here:
https://github.com/raazesh-sainudiin/scalable-data-science
and
https://www.gitbook.com/book/raazesh-sainudiin/scalable-data-science/details
and
http://lamastex.org/courses/ScalableDataScience/

Best,
Raaz

**Comment by MiraLak** [comment]
Hi Raaz,

Of course you can use the data. I didn't have the time to make it anonymous (remove names and replace them with 'user1', 'user2' etc...) so if you can do iy, it will be great.

Nice work by the way!

Regards,

Amira

**Comment by lamastex** [comment]
Hi Amira,
I have anonymised your data here:
http://lamastex.org/datasets/public/ActivityRecognition/dataTraining.csv

But am not able to find the code you used for training the model (instead of just loading the model for prediction). I see you get 15 features from the data. But I am not sure how big you set the window size to be for the mean, standard deviations, etc. What window length did you use?
I am planning to use DataFrames (avoid cassandra) and windowing functions for activity detection with your data: http://xinhstechblog.blogspot.co.nz/2016/04/spark-window-functions-for-dataframes.html
And do it all in databricks notebook.
Raaz

**Comment by lamastex** [comment]
And here is the notebook with anonymized data with 98% accuracy using the last 10 events:
http://lamastex.org/courses/ScalableDataScience/2017/S1/xtraResources/recognizeActivityByRandomForest.html

Thanks again!
Raaz

**Comment by MiraLak** [comment]
Nice work! 
Happy to help 😄 

Amira
